services:
  - type: web
    name: infulx-ventures
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false   # Render asks you to type this when you deploy
      - key: PYTHON_VERSION
        value: 3.12.7
